version: 2
jobs:
  build:
    working_directory: ~/todo
    docker:
      - image: circleci/node:12.8.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependency
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: ~/todo
          paths:
            - build
      - run:
          name: List
          command: ls -al
      - run:
          name: pwd
          command: pwd
